name: Packaging Quality check

# This pipeline will only run when it is manually triggred
on:
  workflow_dispatch:

jobs:
  validate-standards:
    name: Run Standards Validator
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Validation Script
        shell: pwsh
        run: |
          # Only run the check if the work folder exists
          if (Test-Path "Work-Packaging-Standards") {
              Write-Host "Running standards check on Work-Packaging-Standards folder..."
              ./Work-Packaging-Standards/Validate-PackagingStandards.ps1
          } else {
              Write-Host "Folder 'Work-Packaging-Standards' not found. Skipping validation."
          }
